  services:
    postgres:
      image: postgres
      container_name: postgres
      environment:
        POSTGRES_USER: zpalfi
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_DB: piscineds
      expose:
        - 5432
      ports:
        - "5432:5432"
      volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      restart: unless-stopped
      networks:
        - postgres_network
      command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

  volumes:
    postgres_data:

  networks:
    postgres_network:
      driver: bridge