version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      POSTGRES_USER: zpalfi
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/zpalfi/goinfre/subject:/subject
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./scripts:/scripts
    restart: unless-stopped
    networks:
      - postgres_network
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zpalfi -d piscineds -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    environment:
      PGWEB_DATABASE_URL: postgres://zpalfi:mysecretpassword@postgres:5432/piscineds?sslmode=disable
    ports:
      - "5050:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge