version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    # image: postgres:16.4-alpine3.20
    container_name: postgres
    environment:
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      POSTGRES_USER: zpalfi
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - /home/zpalfi/goinfre/subject:/subject
    - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    # - ./scripts:/scripts
    - ./scripts/automatic_table.py:/docker-entrypoint-initdb.d/automatic_table.py
    - ./scripts/items_table.py:/docker-entrypoint-initdb.d/items_table.py
    - ./scripts/table.py:/docker-entrypoint-initdb.d/table.py
    - ./scripts/table_customers.py:/docker-entrypoint-initdb.d/table_customers.py
    - ./scripts/customers_table.py:/docker-entrypoint-initdb.d/customers_table.py
    - ./scripts/custom_entrypoint.sh:/script/custom_entrypoint.sh
    restart: unless-stopped
    networks:
      - postgres_network
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpw
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres_network:
    driver: bridge